<a href="https://colab.research.google.com/github/RabadeJanhvi-45/Titanic-Survival-Prediction-Using-Python/blob/main/Titanic_AdaBoot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#load the dataset
import pandas as pd
import numpy as np

titanic_data=pd.read_csv('/content/drive/MyDrive/AIML B2 DATASETS/titanic.csv')

In [ ]:
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
#Preprocessing of data
#dropping columns
titanic=titanic_data.drop(['PassengerId','Name','Ticket'],axis=1)

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object
 8   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [ ]:
#find unique values of attribute
titanic['Sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
#find null values in each column
print(titanic.isnull().sum())

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [ ]:
#drop cabin because there are more missing vales
titanic=titanic.drop(['Cabin'],axis=1)

In [ ]:
#check the statistical summary of data using
titanic.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
#replace missing vales of age - with 0
titanic['Age']=titanic['Age'].fillna("0")

In [ ]:
print(titanic.isnull().sum())

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       891 non-null    object
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(1), int64(4), object(3)
memory usage: 55.8+ KB

In [ ]:
titanic['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [ ]:
titanic['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [ ]:
titanic['Pclass'].unique()

array([3, 1, 2])

In [ ]:
#inorder to use ONE HOT Encoding convert to string
titanic['SibSp']=titanic['SibSp'].astype(str)

In [ ]:
titanic['Parch']=titanic['Parch'].astype(str)
titanic['Pclass']=titanic['Pclass'].apply(str)

In [ ]:
#encode
gender=pd.get_dummies(titanic['Sex'])

In [ ]:
gender.head()

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

In [ ]:

gender=pd.get_dummies(titanic['Sex'],dtype=int)

In [ ]:
gender

     female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [ ]:
dummy_cat=pd.get_dummies(titanic[['Pclass','Sex','SibSp','Parch','Embarked']],dtype=int)

In [ ]:
dummy_cat.head()

,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,SibSp_0,SibSp_1,SibSp_2,SibSp_3,SibSp_4,...,Parch_0,Parch_1,Parch_2,Parch_3,Parch_4,Parch_5,Parch_6,Embarked_C,Embarked_Q,Embarked_S
0,0,0,1,0,1,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,1
1,1,0,0,1,0,0,1,0,0,0,...,1,0,0,0,0,0,0,1,0,0
2,0,0,1,1,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
3,1,0,0,1,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,1
4,0,0,1,0,1,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1

In [ ]:
final_df=pd.concat([dummy_cat,titanic['Age']],axis=1)#concat is a vertical join

In [ ]:
final_df=final_df.drop(['Sex_male'],axis=1)#concat is a vertical join

In [ ]:
#Prepare x and y for final analysis
x=final_df
y=titanic['Survived']

In [ ]:
#Split the dataset into training and testing
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=45)

In [ ]:
#Build the model
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier

#instamce of classifier
clf1=AdaBoostClassifier(n_estimators=100,learning_rate=1.0,random_state=45)

#train the model
model=clf1.fit(x_train,y_train)

#test the model
y_pred=model.predict(x_test)

In [ ]:
#compute the accuracy of the model
from sklearn.metrics import accuracy_score
print("Accuracy : ",(accuracy_score(y_test,y_pred)*100))

Accuracy :  81.34328358208955

In [ ]:
#change the base classifier
#instamce of classifier
clf2=AdaBoostClassifier(base_estimator=RandomForestClassifier(random_state=45,max_depth=1),n_estimators=100,learning_rate=1.0,random_state=45)

#train the model
model2=clf2.fit(x_train,y_train)

#test the model
y_pred2=model2.predict(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

In [ ]:
#compute the accuracy of the model
from sklearn.metrics import accuracy_score
print("Accuracy : ",(accuracy_score(y_test,y_pred)*100))

Accuracy :  83.5820895522388